def run():
  print("Please enter a character for the eye")
  eye = input()
  print("  #########  ")
  print("##  {}   {}  ##".format(eye,eye))
  print("##  -----  ##")
  print("  #########  ")
  print("    /###\    ")
  print("   /#####\   ")
  print("  //#####\\\  ")
  print("  U ##### U"  )
  print("     ###     ")