def run():
  print("What is your name human?")
  name = str(input())
  print("How old are you? (in years)")
  age = int(input())
  print("How tall are you? (in meters)")
  height = float(input())
  print("How much do you weigh? (in kilograms)")
  weight = float(input())
  bmi = float(weight/height**2)
  print("{} you are {} years old and your bmi is {}".format(name,age,"{:.2f}".format(bmi)))
#Alternatively, bmi = round(weight/height**2, 2)