print("Please enter the number of lives.")
lv = int(input())
print("Please enter the energy level.")
eg = int(input())
print("Please enter the shield level.")
sh = int(input())
print("Health has been set")
print("\n")
print("Lives: {}".format("♥" * lv))
print("Energy: {}".format("♦" * eg))
print("Shield: {}".format("♦" * sh))